parameters:
#    acme_test.example.class: Acme\Bundle\TestBundle\Example

services:
#    acme_test.example:
#        class: %acme_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
