parameters:
#    acme_security.example.class: Acme\SecurityBundle\Example

services:
#    acme_security.example:
#        class: %acme_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
