AcmeSiteBundle:
    resource: "@AcmeSiteBundle/Resources/config/routing.yml"
    prefix:   /

AcmeSecurityBundle:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
